name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Increment JAR version
        run: |
          version=$(cat pom.xml | grep -oPm1 "(?<=<version>)[^<]+")
          new_version=$(echo $version | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          echo "New version: $new_version"
          sed -i "s/<version>$version<\/version>/<version>$new_version<\/version>/" pom.xml
        shell: bash

      - name: Commit updated version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add pom.xml
          git commit -m "Incremented version to $new_version"
          git push
