name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Increment JAR version
        id: increment_version
        run: |
          version=$(cat pom.xml | grep -oPm1 "(?<=<version>)[^<]+")
          new_version=$(echo $version | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          echo "New version: $new_version"
          sed -i "s/<version>$version<\/version>/<version>$new_version<\/version>/" pom.xml
          echo "old_version=$version" >> $GITHUB_ENV
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "::set-output name=new_version::$new_version"
        shell: bash
      - name: Debug version output
        run: |
          echo "Versioning output: ${{ steps.increment_version.outputs.new_version }}"

  build-docker:
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug versioning output
        run: |
          echo "Building Docker image with version: ${{ needs.versioning.outputs.new_version }}"
          echo "Environment version: ${{ env.new_version }}"

      - name: Build Docker image
        run: |
          docker build -t oshri1997/my-app:${{ needs.versioning.outputs.new_version }} .
          docker tag oshri1997/my-app:${{ needs.versioning.outputs.new_version }} oshri1997/my-app:latest

  push-to-registry:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push oshri1997/my-app:${{ needs.versioning.outputs.new_version }}
          docker push oshri1997/my-app:latest
