name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Increment JAR version
        id: increment_version
        run: |
          version=$(cat pom.xml | grep -oPm1 "(?<=<version>)[^<]+")
          new_version=$(echo $version | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          echo "New version: $new_version"
          sed -i "s/<version>$version<\/version>/<version>$new_version<\/version>/" pom.xml
          echo "old_version=$version" >> $GITHUB_ENV
          echo "new_version=$new_version" >> $GITHUB_ENV
        shell: bash

      - name: Commit updated version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add pom.xml
          git commit -m "Incremented version to ${{ env.new_version }}"
          git push
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t oshri1997/my-app:${{ env.new_version }} .
          docker tag oshri1997/my-app:${{ env.new_version }} oshri1997/my-app:latest
          echo "Docker image built and tagged with version ${{ env.new_version }}"

      - name: Push Docker image to Docker Hub
        run: |
          docker push oshri1997/my-app:${{ env.new_version }}
          docker push oshri1997/my-app:latest
          echo "Docker image pushed to Docker Hub"

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
            host: 3.75.199.206
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            port: 22
            script: |
              # Update system packages
              sudo apt update -y
              sudo apt upgrade -y
        
              # Install Docker if not installed
              if ! [ -x "$(command -v docker)" ]; then
                  sudo apt install -y docker.io
                  sudo systemctl start docker
                  sudo systemctl enable docker
              fi
        
              # Pull and run the Docker image
              sudo docker pull oshri1997/my-app:latest
              sudo docker run --rm -d oshri1997/my-app:latest